sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    database: 0
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tCXQvEmeSctuzE38GCG
    access-key-secret: RPB2HmlTi6I1douo5f0rw0rOuNMPnG
    bucket-name: huxi-take-out