sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    database: 0
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALICLOUD_ACCESS_KEY_ID:default_key_id}
    access-key-secret: ${ALICLOUD_ACCESS_KEY_SECRET:default_secret}
    bucket-name: huxi-take-out